### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SteveClement** [EtixLabs/game-of-code-2016#1]
Dear GoC Team,

Please add a LICENSE file so everyone knows how to share, implement, re-use, distribute, modify, improve your code.

It is not the easiest of choices but here is a good start: http://choosealicense.com/

Once chosen just put a file called LICENSE in the root of your Repository :)

Thanks a lot for having been part of the first Game of Code Hackathon, you were AWESOME!

Steve

**Comment by gaelollivier** [comment]
GNU GPL License has been added to the repository
